= First Interactive Component Receiver
:excerpt: This short guide will show you how to set up a Interactive Component receiver
:title: First Interactive Component Receiver

To write your first command receiver you write a component that implements the link:starter/slack-spring-boot/src/main/kotlin/io/olaph/slack/broker/receiver/SlashCommandReceiver.kt[SlashCommandReceiver] interface
you can use the  link:client/slack-api-client/src/main/kotlin/io/olaph/slack/client/SlackClient.kt[SlackClient] that is automatically registered with the starter

Example Ping Receiver that answers with a pong
[source,kotlin]
--
@Component
class PingCommandReceiver @Autowired constructor(private val slackClient: SlackClient) : SlashCommandReceiver {

    override fun supportsCommand(slackCommand: SlackCommand): Boolean {
        return slackCommand.command.startsWith("/ping")
    }

    override fun onReceiveSlashCommand(slackCommand: SlackCommand, headers: HttpHeaders, team: Team) {
        this.slackClient.chat().postMessage(team.bot.accessToken)
                .with(SlackPostMessageRequest(
                        text = "Pong",
                        channel = slackCommand.channelId
                )).invoke()
    }
}

--