= First Event Receiver

:excerpt: This short guide will show you how to set up a Event receiver
:title: First Event Receiver
:order: 4
:source-highlighter: highlightjs

To write your first event receiver you write a component that implements the link:https://github.com/kreait/slack-spring-boot-starter/blob/master/starter/slack-spring-boot/src/main/kotlin/io/olaph/slack/broker/receiver/EventReceiver.kt[EventReceiver] interface you can use the  link:client/slack-api-client/src/main/kotlin/io/olaph/slack/client/SlackClient.kt[SlackClient] that is automatically registered with the starter

Example EventReceiver which sends a message when a channel is renamed (channel_rename permission required)

[source,kotlin]
--
@Component class ChannelRenamedEventReceiver @Autowired constructor(private val slackClient:
SlackClient) :
EventReceiver {

    override fun onReceiveEvent(slackEvent: SlackEvent, headers: HttpHeaders, team: Team) {

        val channelId = (slackEvent.event["channel"] as Map<*, *>)["id"] as String
        val newChannelName = (slackEvent.event["channel"] as Map<*, *>)["name"] as String

        this.slackClient.chat().postMessage(team.bot.accessToken)
                .with(SlackPostMessageRequest(
                        text = "Wow $newChannelName is really cool",
                        channel = channelId
                )).invoke()
    }

    override fun supportsEvent(slackEvent: SlackEvent): Boolean {
        return slackEvent.event["type"] == "channel_rename"
    }
}

--